# 6.1. Модули math и numpy

In [3]:
import math
# Степенные и логарифмические функции. Некоторые из функций:

# math.exp(x) – возвращает значение экспоненциальной функции ex:

print(math.exp(3.5))  # 33.11545195869231
# math.log(x, base) – возвращает значение логарифма от x по основанию base. Если значение аргумента base не задано, то вычисляется натуральный логарифм. Вычисление производится по формуле log(x) / log(base):

print(math.log(10))  # 2.302585092994046
print(math.log(10, 2))  # 3.3219280948873626
# math.pow(x, y) – возвращает значение x в степени y. В отличие от операции ** происходит преобразование обоих аргументов в вещественные числа:

print(math.pow(2, 10))  # 1024.0
print(math.pow(4.5, 3.7))  # 261.1477575641718

33.11545195869231
2.302585092994046
3.3219280948873626
1024.0
261.1477575641718


In [4]:
# Тригонометрические функции. Доступны функции синус (sin(x)), косинус (cos(x)), тангенс (tan(x)),
#  арксинус (asin(x)), арккосинус (acos(x)), арктангенс (atan(x)). Обратите внимание: угол задаётся
#  и возвращается в радианах. Имеются особенные функции:

# math.dist(p, q) – возвращает Евклидово расстояние между точками p и q, заданными как итерируемые объекты одной длины:

print(math.dist((0, 0, 0), (1, 1, 1)))  # 1.7320508075688772
# math.hypot(*coordinates) – возвращает длину многомерного вектора с координатами, 
# заданными в позиционных аргументах coordinates, и началом в центре системы координат. 
# Для двумерной системы координат функция возвращает длину гипотенузы прямоугольного треугольника по теореме Пифагора:

print(math.hypot(1, 1, 1))  # 1.7320508075688772
print(math.hypot(3, 4))  # 5.0

# Функции преобразования угла. Доступны функции:

# math.degrees(x) – преобразует угол из радиан в градусы:

print(round(math.sin(math.radians(30)), 1))  # 0.5

# math.radians(x) – преобразует угол из градусов в радианы.

print(round(math.degrees(math.asin(0.5)), 1))  # 30.0
# Гиперболические функции. Доступны функции acosh(x), asinh(x), atanh(x), cosh(x), sinh(x), tanh(x).

# Специальные функции. Среди специальных функций интерес представляет Гамма-функция.
#  Она описывает гладкую непрерывную функцию f(x) = (x - 1)!, график которой проходит через точки, 
# соответствующие значениям функции факториала для целых чисел. Другими словами, 
# Гамма-функция интерполирует значения факториала для вещественных чисел:

print(math.gamma(3))  # 2.0
print(math.gamma(3.5))  # 3.323350970447842
print(math.gamma(4))  # 6.0
 
# В библиотеке math можно воспользоваться значениями числа Пи (math.pi) и экспоненты (math.e).

# Язык программирования Python удобен для быстрого создания программ с целью проверки какой-либо идеи. 
# Однако зачастую его используют и в решении научных задач, а также при анализе больших данных и машинном обучении. 
# Возникает вопрос: каким образом может быстро обрабатывать много данных интерпретируемая, 
# а не скомпилированная программа? Оказывается, что в решении некоторых математических 
# задач программы на Python могут быть такими же быстрыми, как и программы, созданные на компилируемых языках.

1.7320508075688772
1.7320508075688772
5.0
0.5
30.0
2.0
3.323350970447842
6.0


## Библиотека numpy является нестандартной библиотекой.

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"a[0] = {a[0]}")
print(f"b[0] = {b[0]}")

a[0] = 1
b[0] = [1 2]


В терминологии numpy `массив a имеет одну ось (термин "axis" из документации) длиной 4 элемента`, а массив `b имеет 2 оси`: первая имеет длину 4, а длина второй оси равна 2.

Массивы numpy являются объектами класса ndarray. Наиболее важными атрибутами класса ndarray являются:

ndarray.ndim – размерность (количество осей) массива;

ndarray.shape – кортеж, значения которого содержат количество элементов по каждой из осей массива;

ndarray.size – общее количество элементов массива;

ndarray.dtype – объект, описывающий тип данных элементов массива;

ndarray.itemsize – размер памяти в байтах, занимаемый одним элементом массива.

In [6]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}, a.size = {a.size}, a.dtype = {a.dtype}")

a.ndim = 2, a.shape = (4, 2), a.size = 8, a.dtype = int64


Покажем на примере, что произойдёт, если попытаться записать значение не из диапазона для типа данных. Для этого создадим массив типа uint8 – целые числа без знака размером 8 бит. Диапазон значений для этого типа от 0 до 255. Тип данных можно указать через именованный аргумент dtype при создании массива:

In [7]:
a = np.array([1, 2, 3], dtype="uint8")
a[0] = 256
print(a)

[0 2 3]


/var/folders/77/k237slcs6gv41pmr9lvp716w0000gn/T/ipykernel_54772/1274961828.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a[0] = 256


В примере для массива a был выбран тип данных float64, так как исходный список содержит вещественное число.` Для массива b был выбран тип данных <U32`, который может хранить строки в кодировке Unicode длиной 32 символа. Такой тип данных был выбран, поскольку в исходной коллекции есть элемент-строка.

In [8]:
a = np.array([1, 2.5, 3])
print(a)
print(a.dtype)
b = np.array(['text', 1, 2.5])
print(b)
print(b.dtype)

[1.  2.5 3. ]
float64
['text' '1' '2.5']
<U32


Для создания массива из нулей используется функция np.zeros(), который принимает кортеж с количеством чисел, соответствующим количеству осей массива, а значения в кортеже – количество элементов по каждой из осей.

In [10]:
a = np.zeros((4, 3))
print(a)
print()
a = np.zeros((4, 3), dtype="int32")
print(a)
a = np.ones((4, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Для создания массива, заполненного значениями из диапазона, используется функция `np.arange()`. Эта функция похожа на стандартную функцию range(), но возвращает массив и может создавать диапазон значений из вещественных чисел.

In [11]:
a = np.arange(1, 10)
print(a)
print()
a = np.arange(1, 5, 0.4)
print(a)

[1 2 3 4 5 6 7 8 9]

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [12]:
# Функция np.linspace() создаёт массив из заданного количества вещественных 
# равномерно-распределённых значений из указанного диапазона.
a = np.linspace(1, 5, 10)  # задаётся начало, конец диапазона и количество значений
print(a)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [13]:
a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 6))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
# Если при изменении размерности в функции reshape() указать значение -1 по одной 
# или нескольким осям, то значения размерности рассчитаются автоматически:
a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 3, -1))
print(a)

In [14]:
# Метод resize() меняет размерность исходного массива:

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a.resize((2, 2, 3))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [15]:
a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[10 10 10]
[8 6 4]
[ 9 16 21]
[9.         4.         2.33333333]


## Для умножения матриц используется операция @ или функция dot:

In [16]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
print(a @ b)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [17]:
# Матрицы можно транспонировать функцией transpose() и поворачивать функцией rot90(). 
# При повороте можно указать направление поворота вторым аргументом:

a = np.arange(1, 13).reshape(4, 3)
print(a)
print("Транспонирование")
print(a.transpose())
print("Поворот вправо")
print(np.rot90(a))
print("Поворот влево")
print(np.rot90(a, -1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Транспонирование
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Поворот вправо
[[ 3  6  9 12]
 [ 2  5  8 11]
 [ 1  4  7 10]]
Поворот влево
[[10  7  4  1]
 [11  8  5  2]
 [12  9  6  3]]


In [18]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(a.sum())
print(a.min())
print(a.max())

45
1
9


In [19]:
# Дополнительно в указанных функциях можно указать номер оси (индексация с 0), на которой будет работать функция:

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum(axis=0))  # сумма чисел в каждом столбце
print(a.sum(axis=1))  # сумма чисел в каждой строке
print(a.min(axis=0))  # минимум по столбцам
print(a.max(axis=1))  # максимум по строкам

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


# срезы

In [20]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print(a[:2, 2:])
print()
print(a[:, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[3 4]
 [7 8]]

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [22]:
# цикл FOR для прохождения по массиву

a = np.arange(1, 13).reshape(3, 4)
print(a)
for row in a:
    print(row)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


#### Для линеаризации многомерного массива можно использовать атрибут flat, который является итератором, возвращающим последовательно значения массива:

In [21]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print("; ".join(str(el) for el in a.flat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12


In [23]:
import numpy as np
from time import time

t = time()
print(f"Результат итератора: {sum(x ** 0.5 for x in range(10 ** 7))}.")
print(f"{time() - t} с.")
t = time()
print(f"Результат numpy: {np.sqrt(np.arange(10 ** 7)).sum()}.")
print(f"{time() - t} с.")

Результат итератора: 21081849486.439312.
1.0495250225067139 с.
Результат numpy: 21081849486.442448.
0.04241490364074707 с.
